dist: trusty
sudo: required
language: scala
scala:
   - 2.11.12
   - 2.12.7
jdk:
  - oraclejdk8
before_install:
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get -y remove --purge postgresql-9.1
  - sudo apt-get -y remove --purge postgresql-9.2
  - sudo apt-get -y remove --purge postgresql-9.3
  - sudo apt-get -y remove --purge postgresql-9.4
  - sudo apt-get -y remove --purge postgresql-9.5
  - sudo apt-get -y remove --purge postgresql-9.6
  - sudo apt-get -y autoremove
  - sudo apt-key adv --keyserver keys.gnupg.net --recv-keys 7FCC7D46ACCC4CF8
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main 11" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update
  - sudo apt-get -y install postgresql-11 postgresql-contrib-11 postgresql-11-postgis-2.5
  - sudo sh -c 'echo "local all postgres trust" > /etc/postgresql/11/main/pg_hba.conf'
  - sudo sh -c 'echo -n "host all all 127.0.0.1/32 trust" >> /etc/postgresql/11/main/pg_hba.conf'
  - sudo service postgresql restart 11
before_script:
  - psql -c 'create database test;' -U postgres
  - psql test -c 'CREATE EXTENSION IF NOT EXISTS hstore;' -U postgres
  - psql test -c 'CREATE EXTENSION IF NOT EXISTS ltree;' -U postgres
  - psql test -c 'CREATE EXTENSION IF NOT EXISTS postgis;' -U postgres
  - psql test -c 'CREATE EXTENSION IF NOT EXISTS pg_trgm;' -U postgres
